server: 
  port: 8888

spring:
  application:
    name: inetum-config 
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jdiazbasgit/configuracionCloudServerInetum.git
